* Mini RPG Game
** Overworld
*** Fighting
	Fighting is done using a turn based system.  Each character has a speed stat that will determine how often they get to fight.
	When the battle starts, every character gets a timer that when it goes off, is that characters turn to fight
	There will be a list of characters pending to do the actual fight, as we may have a queue of actions setup
	When the characters timer goes off, we should show a battle menu for that character, and after selecting the action, that will go into the list
	Enemy monsters also will have a speed stat that will determine when they get to go.
** Game Menu
*** Status Menu
	This menu shows the current list of characters that are a part of the party.  An info button can be clicked to view character stats and their current equpiment.
**** Character Equip Menu
	 This menu lets you equip items on a character.  Each slot has a button that can be clicked to select a new item.
*** Items Menu
	A list of items that the party has access to.
	- Do we list equipped items?
*** Save Menu
	This menu lets you save the game
	- TODO Add info (time and screenshot?) of the last save game


* Todo
** Controller Stuff
	- Fix the load game screen so that you can control it with a controller
	- Same with new game screen
	- Setup game menu to use controller
	- Figure out best way to do keyboard input with a controller
** Misc
- Check into: https://www.reddit.com/r/godot/comments/pqvdfs/finally_my_tool_that_adds_postprocessing_effects/ to make game look more retro

