on:
  release:
    types: [published]

jobs:
  release_html5:
    runs-on: ubuntu-latest
    steps:
      - name: download web build
        id: download-web
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: HTML5.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Windows)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: HTML5
          ITCH_GAME: MiniRPG
          ITCH_USER: majormunky
          PACKAGE: HTML5.zip
          VERSION: ${{ steps.download-web.outputs.version }}
